name: windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2019
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules : true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Add MSVC to PATH
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: win64
        
    - name: Add NASM to PATH
      uses: ilammy/setup-nasm@v1
      with:
        platform: win64
          
    - name: Add perl
      uses: shogo82148/actions-setup-perl@v1
      
    - name: Generate ARTIFACT_VERSION
      run: echo ARTIFACT_VERSION=$((Get-Date).tostring("yyyy.MMdd.HHmm")) >> $env:GITHUB_ENV
      
    - name: Create Build Dir
      run: mkdir build_openssl
      
    - name: Configure build_openssl
      working-directory: build_openssl
      run: |
        perl ..\openssl\Configure --banner=Configured no-makedepend no-shared enable-fips enable-quic VC-WIN64A
        perl configdata.pm --dump

    - name: Build Debug
      working-directory: build_openssl
      run: |
        nmake clear
        nmake

    - name: Pack NuGet (Package)
      run: nuget pack openssl-clarity.nuspec -p version=$env:ARTIFACT_VERSION

    - name: Publish NuGet
      if: github.event_name != 'pull_request'
      run: |
        nuget sources Add -Name github -Source https://nuget.pkg.github.com/${{github.repository_owner}}/index.json -Username ${{github.repository_owner}} -Password ${{github.token}}
        nuget push *.nupkg -Source github -SkipDuplicate -ApiKey ${{github.token}}
